language: erlang
addons:
    apt:
      packages:
      - sqlite3
      - libgmp-dev
install:
    - epmd -daemon
otp_release:
    - 23.1.2
# blocklist
branches:
    except:
    - master
# AR UT
script:
    - ./bin/test
