# See: https://github.com/weavery/gitstamp-action
---
name: Gitstamp
on: 
  push:
    branches:
      - 'master'
      - 'release/**'
      - 'releases/**'
  pull_request_target:
    types: [closed]

jobs:
  gitstamp:
    runs-on: [self-hosted, ubuntu, amd64, build-runner]
    name: Timestamp commit with Gitstamp
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Submit Gitstamp transaction
        uses: weavery/gitstamp-action@v1
        with:
          wallet-key: ${{ secrets.GITSTAMP_KEYFILE }}
          commit-link: true
